### ISSUE TITLE
Monomers Not Joining

### ISSUE THREAD

**Issue by johnsantamariajr** [Boehringer-Ingelheim/pyPept#4]
Hey Team,
   Thanks for a great release, I've been excited to try this out with our monomers. I converted our monomer dictionary to resemble the provided monomer file, making sure to match up all the attachment point idx, group idx, the R groups, etc. 

However, when providing biln mapping to the new monomer.sdf, monomers will no longer join. The N-cap will join onto the 1st monomer, but every monomer after that will be separate.
e.g.
biln = 'ac-L-A-am'
seq=Sequence(biln)
mol = Molecule(seq)
mol2 = mol.get_molecule(fmt='ROMol')

produces acetylated leucine, followed by a separate alanine and a separate NH2 group.

Any idea what could be happening? Been stuck on this for a while. Thanks!

**Comment by foxth** [comment]
Can you send me your monomer sdf file (just the 4 monomers you mention)? Then I can try to reproduce your findings and see how to fix it.Thanks,Th.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 27.12.23, 22:27 schrieb John Santa Maria ***@***.***>:

   
  Hey Team, Thanks for a great release, I've been excited to try this out with our monomers. I converted our monomer dictionary to resemble the provided monomer file, making sure to match up all the attachment point idx, group idx, the R groups, etc. 
  However, when providing biln mapping to the new monomer.sdf, monomers will no longer join. The N-cap will join onto the 1st monomer, but every monomer after that will be separate. e.g. biln = 'ac-L-A-am' seq=Sequence(biln) mol = Molecule(seq) mol2 = mol.get_molecule(fmt='ROMol') 
  produces acetylated leucine, followed by a separate alanine and a separate NH2 group. 
  Any idea what could be happening? Been stuck on this for a while. Thanks!

**Comment by johnsantamariajr** [comment]
Thanks for the quick reply!
Please note that my monomers are actually called Ac,Leu, Ala, and NH2, so the true command was:
biln = 'Ac-Leu-Ala-NH2'
The scrubbed monomer dict is attached as a .zip because .sdf is apparently unsupported by Github. I have reproduced this error with the attached file to confirm. Thanks :)
[monomers.sdf.zip](https://github.com/Boehringer-Ingelheim/pyPept/files/13781830/monomers.sdf.zip)

**Comment by foxth** [comment]
Ok, I can reproduce your findings with your monomer.sdf, with the supplied monomers.sdf in the repo things work as they should (puuh, for a short while I was really worried!!). Ok, then there is something fishy in your monomer file. I think I found it: your atom ordering is different, yet you haven't updated the m_RgroupIdx and m_attachmentPointIdx pointers (the first being the atom indices of the R-groups, the second the indices of the atoms these R-groups are attached to. 

So, Ac works fine, as there you have the R2 as atom #3, connected to #1, but for Leucine your R-groups are at position 6 and 9, yet your m_RgroupIdx is "8,9,None, None".  Same is true for Ala: your Rgroups are at positions #3 and #6, yet your m_RgroupIdx is 5 and 6. Thinking a bit more about it: I always move the R-group atoms last in the molblock - then you dont have to change the indices of the other atoms if you remove any of it to make a bond.

Sooo - first of all there should be some warnings: a) when the Rgroups are not last in the molblock and b) when molblock and index pointers do not agree. How did you create the monomer.sdf? Maybe there should be a script to a) check if molblock and indices match, or even better, one that creates the indices from the molblock. After all, the information is already there... I believe I do this somewhere in our internal version of pyPept, let me see how easy it is to extract that code.

Hope this helps,
Th.

**Comment by johnsantamariajr** [comment]
Good day,
   Thank you for looking further into this! I had created this monomers.sdf by loading in my monomers.sdf and lifting the guts of the generate_monomers function in map_monomers.py as shown below.
   
   `# Extract the indices
        r_group_idx = [None, None, None, None]
        attachment_idx = [None, None, None, None]
        r_groups=[r1_group,r2_group,r3_group,r4_group]

        if p_type == "PEPTIDE":
            for atom_val in mol.GetAtoms():
                if atom_val.GetSymbol()[0]=='R':
                    label=int(atom_val.GetSymbol()[1])
                    root_atom = atom_val.GetNeighbors()[0]
                    r_group_idx[label-1]=atom_val.GetIdx()
                    attachment_idx[label-1]=root_atom.GetIdx()

            # Generate a PDB code for the monomer
            pdb_code = generate_pdb_code(symbol, list_pdbs)
            list_pdbs.append(pdb_code)

            # Add the SDF tags
            mol.SetProp('m_name', name)
            mol.SetProp('symbol', symbol)
            mol.SetProp('m_abbr', symbol)
            mol.SetProp('m_type', cat_type)
            mol.SetProp('m_subtype', cat_sub)
            new_r_groups=[str(x) for x in r_groups]
            mol.SetProp('m_Rgroups', ','.join(new_r_groups))
            new_r_group_idx=[str(x) for x in r_group_idx]
            mol.SetProp('m_RgroupIdx', ','.join(new_r_group_idx))
            new_attachment_idx=[str(x) for x in attachment_idx]
            mol.SetProp('m_attachmentPointIdx', ','.join(new_attachment_idx))
            mol.SetProp('natAnalog', natural_a)
            mol.SetProp('pdbName', pdb_code)
            writer.write(mol)`

 I also ended up reversing a few things because our internal monomers had R1 and R2 switched relative to the package. I will try converting the indices and see if that rectifies the problem. Again, very grateful you were able to identify the issue, thank you :)

**Comment by foxth** [comment]
Maybe the following two functions are helpful when setting up your monomer sd-file: the first moves the R-group labels to the end of the atom list, the second extracts the atom indices of the R-groups and the connecting atoms:
````
    maxNoRgroups = 3  # max number of R-groups in a monomer, for peptides usually 3

    def __RgroupsToEnd(self):
        """Move R groups to the end of the mol block

        In the monomer ROMol, the R groups must be at the end of the mol block. Otherwise it may happen that the romol
        and the attachmentpoint index are out of sync. If during processing an R group is removed, the attachmentpoint
        info must be updated in case after the Rgroup an attachment point atom is in the mol block. It seems easier to
        just move all the Rgroups to the end of the mol block.

        Returns:

        """

        newIdx = list(range(0, self.m_romol.GetNumAtoms()))

        for i in self.m_RgroupIdx:
            if i is not None:
                newIdx.remove(i)
                newIdx.append(i)

        self.m_romol = Chem.RenumberAtoms(self.m_romol, newIdx)


    def __findRgroupIndices(self):
        """analyze the romol object to find the atom seqIDs of the atoms the R-groups are attached to
           this is then saved in the attachmentPoints vector
        """
        romol = self.m_romol

        if romol is None:
            self.m_attachmentPointIdx = [None]
            return

        RgroupIdx = [None] * maxNoRgroups
        attachmentPointIdx = [None] * maxNoRgroups

        # step through the atoms in romol and check if they are a R-group, i.e. if they have the property _MolFileRLabel
        # if so, keep the indices of the atom and the connecting atom and put them into Rtmp and RGtmp

        for at in romol.GetAtoms():
            # print (at.GetIdx(), ': ', at.GetAtomicNum())
            try:
                rLabel = int(at.GetProp('_MolFileRLabel'))
                rLabel += -1  # Rgroup labels start from 1

                rootAtom = at.GetNeighbors()[0]
                attachmentPointIdx[rLabel] = rootAtom.GetIdx()
                RgroupIdx[rLabel] = at.GetIdx()

            except:
                pass

        # print R-groups
        msg = []
        for i in range(0,4):
           msg.append('rgroup {} @atom is connected to: {}, will be replaced by {}'
                         .format(i, RgroupIdx[i], attachmentPointIdx[i], self.m_Rgroups[i]))
        msg = '\n'.join(msg)
        monomer_logger.debug(msg)

        self.m_RgroupIdx = RgroupIdx
        self.m_attachmentPointIdx = attachmentPointIdx

```
This way you can set up your sdfile which whatever pipeline you want, and then only at the end, read it in with rdkit and correct the indices as needed.
