### ISSUE TITLE
Adding crosslinking monomers

### ISSUE THREAD

**Issue by amin-sagar** [Boehringer-Ingelheim/pyPept#9]
Hello.
Thanks for this awesome work.
I am trying to understand the way to add scaffolds to the monomer sdf file. For example, 1,3,5-trismethylbenzene was used in https://pubs.acs.org/doi/10.1021/acs.jcim.2c00703
![image](https://github.com/user-attachments/assets/042d3b1b-37e9-4dcc-9567-9dfaaad77c7a)
It is described in BILN-converter (https://github.com/rochoa85/BILN-converter) as 
![image](https://github.com/user-attachments/assets/15c32975-4f7a-4ef5-b483-5f1935a45d66)
The scaffold with atom numbers looks like this.
![image](https://github.com/user-attachments/assets/ddfcea3d-aa1e-4045-af9c-e4a748f6e5f6)

I tried making an entry for monomer sdf as follows
```
TMB_3.sdf
  ChemDraw10042408332D

 12 12  0  0  0  0  0  0  0  0999 V2000
    1.7862    1.0312    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0717    0.6188    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0717   -0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3572   -0.6188    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3572   -1.4438    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3572   -0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3572    0.6188    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0717    1.0312    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3572    1.0312    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7862    1.8562    0.0000 R#  0  0  0  0  0  0  0  0  0  0  0  0
    1.0717   -1.8562    0.0000 R#  0  0  0  0  0  0  0  0  0  0  0  0
   -1.7862    0.6188    0.0000 R#  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0        0
  2  3  1  0        0
  3  4  2  0        0
  4  5  1  0        0
  4  6  1  0        0
  6  7  2  0        0
  7  8  1  0        0
  7  9  1  0        0
  2  9  2  0        0
  1 10  1  0        0
  5 11  1  0        0
  8 12  1  0        0
M  RGP  3   10   1   11   2   12   3
V    10 *
V    11 *
V    12 *
M  END
>  <m_name>  (2) 
1,3,5-trismethylbenzene

>  <symbol>  (2) 
135_TMB

>  <m_abbr>  (2) 
135_TMB

>  <m_type>  (2) 
aa

>  <m_subtype>  (2) 
non-natural

>  <m_Rgroups>  (2) 
H,H,H,None

>  <m_RgroupIdx>  (2) 
9,10,11,None

>  <m_attachmentPointIdx>  (2) 
0,4,7,None

>  <natAnalog>  (2) 
X

>  <pdbName>  (2) 
TMB
$$$$
```

Edit: Sorry, I edited the issue as there was a problem with the <m_attachmentPointIdx> entry.
Am I going in the right direction?
What should the m_type be in this case? It's not really an amino acid or a cap. Do I need a different m_type?

I tried using aa as m_type. If I add this to the monomer.sdf, the scaffold is recognized, the correct smiles are produced.
```
CC(C)C[C@@H]1NC(=O)[C@H](CC(=O)O)NC(=O)[C@H](CCC(N)=O)NC(=O)[C@H](Cc2c[nH]cn2)NC(=O)[C@H](CC(C)C)NC(=O)[C@@H]2CSCc3cc(cc(c3)CSC[C@H](N)C(=O)N[C@@H](CO)C(=O)N[C@@H](Cc3c[nH]c4ccccc34)C(=O)N3CCC[C@H]3C(=O)N[C@@H](C)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N2)CSC[C@@H](C(=O)O)NC1=O
```
But the conformation generation keeps running for at least an hour. If I pass the --noconf flag, the following image is produced which seems correct except the slight distortion.

![image](https://github.com/user-attachments/assets/ebd013fb-e673-4a2f-b660-25f2d6ac2346)

Could the conformation generator be stuck because of the m_type?
I would be really grateful for any suggestions.
Best,
Amin.

**Comment by foxth** [comment]
Ah, you want to use "linker" as m_type, and then an empty m_subtype. "natAnalog" I would leave empty as well. All the other things look ok to me.

 

Best,

Th.

 
 

Gesendet: Freitag, 04. Oktober 2024 um 09:54 Uhr
Von: "amin-sagar" ***@***.***>
An: "Boehringer-Ingelheim/pyPept" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [Boehringer-Ingelheim/pyPept] Adding crosslinking monomers (Issue #9)


 

Hello.
Thanks for this awesome work.
I am trying to understand the way to add scaffolds to the monomer sdf file. For example, 1,3,5-trismethylbenzene was used in https://pubs.acs.org/doi/10.1021/acs.jcim.2c00703
image.png (view on web)
It is described in BILN-converter (https://github.com/rochoa85/BILN-converter) as
image.png (view on web)
The scaffold with atom numbers looks like this.
image.png (view on web)

I tried making an entry for monomer sdf as follows

TMB_3.sdf
  ChemDraw10042408332D

 12 12  0  0  0  0  0  0  0  0999 V2000
    1.7862    1.0312    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0717    0.6188    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0717   -0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3572   -0.6188    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3572   -1.4438    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3572   -0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3572    0.6188    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0717    1.0312    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3572    1.0312    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7862    1.8562    0.0000 R#  0  0  0  0  0  0  0  0  0  0  0  0
    1.0717   -1.8562    0.0000 R#  0  0  0  0  0  0  0  0  0  0  0  0
   -1.7862    0.6188    0.0000 R#  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0        0
  2  3  1  0        0
  3  4  2  0        0
  4  5  1  0        0
  4  6  1  0        0
  6  7  2  0        0
  7  8  1  0        0
  7  9  1  0        0
  2  9  2  0        0
  1 10  1  0        0
  5 11  1  0        0
  8 12  1  0        0
M  RGP  3   10   1   11   2   12   3
V    10 *
V    11 *
V    12 *
M  END
>  <m_name>  (2)
1,3,5-trismethylbenzene

>  <symbol>  (2)
123_TMB

>  <m_abbr>  (2)
123_TMB

>  <m_type>  (2)
aa

>  <m_subtype>  (2)
non-natural

>  <m_Rgroups>  (2)
H,H,H,None

>  <m_RgroupIdx>  (2)
9,10,11,None

>  <m_attachmentPointIdx>  (2)
0,4,8,None

>  <natAnalog>  (2)
X

>  <pdbName>  (2)
TMB
$$$$


Am I going in the right direction?
What should the m_type be in this case? It's not really an amino acid or a cap. Do I need a different m_type?
I would be really grateful for any suggestions.
Best,
Amin.

**Comment by amin-sagar** [comment]
Perfect. Thanks.
